### ISSUE TITLE
Update to 2.13.6

### ISSUE THREAD

**Issue by mflorea** [webjars/jshint#20]
The latest upstream version is now 2.13.6. See https://github.com/jshint/jshint/releases . Please release a new version.

Note that the ``org.webjars.npm`` version (that can be automatically published) is currently unusable unfortunately:

```
Could not resolve version conflict among [org.webjars.npm:jshint:jar:2.13.6 -> org.webjars.npm:minimatch:jar:[3.0.2,3.1), org.webjars.npm:jshint:jar:2.13.6 -> org.webjars.npm:cli:jar:[1.0.0,1.1) -> org.webjars.npm:glob:jar:[7.1.1,8) -> org.webjars.npm:minimatch:jar:[3.1.1,4)]
```

So the only option seems to be to update and publish the ``org.webjars`` version manually :(

Thanks.

**Comment by mflorea** [comment]
Actually there is another option, exclude all transitive dependencies:

```
<dependency>
  <groupId>org.webjars.npm</groupId>
  <artifactId>jshint</artifactId>
  <version>2.13.6</version>
  <!-- Exclude all transitive dependencies because they aren't really needed and, what's worse, they fail the build. -->
  <exclusions>
    <exclusion>
      <groupId>*</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

So publish the new version only when / if you find the time. Thanks.

**Comment by jamesward** [comment]
The NPM WebJar issue is interesting but I'm not sure if it is something we can fix because the version ranges are generated from the NPM packages.  What the error is saying is that:

`org.webjars.npm:jshint:jar:2.13.6` depends on `org.webjars.npm:minimatch:jar:[3.0.2,3.1)`

And that
`org.webjars.npm:jshint:jar:2.13.6` depends on `org.webjars.npm:cli:jar:[1.0.0,1.1)` which depends on `org.webjars.npm:glob:jar:[7.1.1,8)` which depends on `org.webjars.npm:minimatch:jar:[3.1.1,4)]`

And the version ranges for the two `minimatch` dependencies are unresolvable because one must be less than `3.1` and the other must be greater than or equal to `3.1.1`.

It is possible that we have a bug in how we are generating those ranges or it could be that NPM is more lenient.  Let me know if you want to dive into this.  :)
